/**
 * composeMinigame — given a chosen (input, rule) pairing and an ICE value,
 * produces the actual playable content: grid values, target number, time
 * limit, etc.
 *
 * Content generation is scoped per-pairing (keyed by "inputKey:ruleKey")
 * rather than fully decoupled from both axes. The honest reason: what
 * content a grid-select input needs already depends on which rule is going
 * to read the picks back — exact-sum needs a reachable target number; a
 * future "reveal-all" rule wouldn't need a target at all, it'd need a
 * decoy/signal split instead. This is a deliberate compromise, not the
 * final architecture. As more inputs/rules land, watch for content logic
 * that turns out identical across every pairing that shares an input (or a
 * rule), and hoist that piece out of this map when it does.
 */
import { tierForIce } from './difficultyScaling.js';

function shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
}

// grid_select + exact_sum — first proof pairing. Player selects any subset
// of cells; win rule checks the selected values sum to the target exactly.
// Target is generated by summing a real random subset of the grid's own
// values, which guarantees at least one valid solution exists.
function composeGridSelectExactSum(ice) {
    const tier = tierForIce(ice);

    const rows    = 5;
    const cols    = 5 + tier * 2; // Tier 1: 7, Tier 2: 9, Tier 3: 11, Tier 4: 13
    const minPick = 2 + tier;     // Tier 1: 3 .. Tier 4: 6
    const maxPick = minPick + 2;  // Tier 1: 5 .. Tier 4: 8

    const values = Array.from({ length: rows }, () =>
        Array.from({ length: cols }, () => 1 + Math.floor(Math.random() * 9))
    );

    const coords = [];
    for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) coords.push([r, c]);
    }
    shuffle(coords);

    const pickCount = minPick + Math.floor(Math.random() * (maxPick - minPick + 1));
    const solution  = coords.slice(0, pickCount);
    const target    = solution.reduce((sum, [r, c]) => sum + values[r][c], 0);

    const timeLimitSec = Math.max(30, 90 - tier * 12);

    return { rows, cols, values, target, timeLimitSec };
}

const CONTENT_GENERATORS = {
    'grid_select:exact_sum': composeGridSelectExactSum,
};

export function composeMinigame({ inputKey, ruleKey, ice }) {
    const genKey     = `${inputKey}:${ruleKey}`;
    const generator  = CONTENT_GENERATORS[genKey];
    if (!generator) {
        throw new Error(`[composer] No content generator registered for pairing "${genKey}".`);
    }
    return { inputKey, ruleKey, ice, content: generator(ice) };
}

/** Pairing keys that currently have a content generator wired up. */
export function availablePairingKeys() {
    return Object.keys(CONTENT_GENERATORS);
}
